- name: bug
  color: d73a4a
  description: Something is not working

- name: enhancement
  color: a2eeef
  description: New feature or improvement

- name: pricing
  color: 1d76db
  description: Pricing data or pricing schema changes

- name: api
  color: 0e8a16
  description: API behavior, contracts, or handlers

- name: documentation
  color: 0075ca
  description: Documentation updates

- name: ci
  color: 5319e7
  description: CI, workflows, and automation

- name: good first issue
  color: 7057ff
  description: Good for first-time contributors

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: breaking-change
  color: b60205
  description: Introduces a breaking change

- name: question
  color: d876e3
  description: Further information is requested

- name: maintenance
  color: cfd3d7
  description: Repository maintenance tasks
